import Link from "next/link";
import LegalPage, { Item } from "@/components/LegalPage";
import { OPERATOR_NAME, CONTACT_EMAIL, MINIMUM_AGE } from "@/lib/legal";

export const metadata = {
  title: "Terms & Conditions",
  description: "The rules for using Graze, and the limits of what it promises.",
};

export default function Terms() {
  return (
    <LegalPage
      title="Terms & Conditions"
      intro="Plain terms for a free, non-commercial research tool. By creating an account or posting, you agree to these."
    >
      <h2>Who runs Graze</h2>
      <p>
        {OPERATOR_NAME} is an independent, non-commercial project run by one person. It is
        free to use: nothing on the site charges money, there is no advertising, and your
        data is not sold. Contact:{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>Age requirement</h2>
      <p>
        <strong>You must be at least {MINIMUM_AGE} to create an account.</strong> Graze has no
        age-verification or parental-consent process, so it cannot lawfully handle accounts
        for children. If you are under {MINIMUM_AGE}, please don&apos;t sign up. Accounts
        found to belong to someone younger will be removed.
      </p>

      <h2>What Field-Tested does and does not mean</h2>
      <p>
        This is the most important thing on this page, so it is stated plainly.
      </p>
      <p>
        The <strong>Field-Tested</strong> badge reports the result of{" "}
        <strong>automated checks against public databases</strong>: whether the publisher
        records the work as peer-reviewed, whether its journal appears in the Directory of
        Open Access Journals, whether a retraction notice exists in the Retraction Watch data
        distributed by Crossref, and how many citations other works have recorded.
      </p>
      <p>
        <strong>
          It is not a judgement of whether a paper is good, correct, reliable, or safe to act
          on.
        </strong>{" "}
        A peer-reviewed paper in a listed journal can still be wrong, and an unlisted or
        preprint paper can still be excellent. The checks can be out of date, incomplete, or
        mistaken — they depend on third-party databases that Graze does not control. Reading
        the source and forming your own judgement is the point of the site, and no badge
        replaces that.
      </p>
      <p>
        The same applies to <strong>&quot;Chew on this&quot;</strong> summaries. They are
        generated by a language model from a paper&apos;s title and abstract, may be
        incomplete or wrong, and are a starting point for reading the paper — not a
        substitute for it.
      </p>
      <p>
        <strong>
          Nothing on Graze is medical, legal, financial, or professional advice.
        </strong>{" "}
        Do not make decisions that affect your health, safety, money, or legal position based
        on a summary or a badge on this site.
      </p>

      <h2>Your content is public</h2>
      <p>
        Papers you submit, comments you write, and the fields you assign are{" "}
        <strong>public</strong> — visible to anyone on the internet, signed in or not. Files
        you upload are stored with public access, so anyone holding the link can open them.
        Posting anonymously hides your display name but is pseudonymous, not anonymous; see
        the <Link href="/privacy">Privacy Policy</Link>.
      </p>
      <p>
        You keep ownership of what you write. By posting it you grant Graze a non-exclusive,
        worldwide, royalty-free licence to store, display and distribute it as part of the
        site. You can ask for your content to be removed — see Ending your account below.
      </p>
      <p>
        By submitting a paper or a file you confirm you have the right to share it, and that
        doing so does not infringe anyone&apos;s copyright or licence terms. Do not upload
        paywalled PDFs you are not licensed to redistribute. If you hold rights in something
        posted here without permission, email{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> and it will be taken down.
      </p>

      <h2>Acceptable use</h2>
      <p>Don&apos;t:</p>
      <ul>
        <Item>Post unlawful, harassing, hateful, or threatening content.</Item>
        <Item>
          Impersonate anyone, or misrepresent your connection to a paper or its authors.
        </Item>
        <Item>
          Post content you don&apos;t have the right to share, or that infringes copyright.
        </Item>
        <Item>
          Deliberately submit fabricated, plagiarised, or knowingly retracted research as
          though it were sound.
        </Item>
        <Item>
          Attempt to break, overload, or gain unauthorised access to the site, other
          people&apos;s accounts, or the systems behind it.
        </Item>
        <Item>
          Scrape the site or automate it at a volume that degrades it for other people.
        </Item>
        <Item>Use Graze to advertise, spam, or promote a commercial product.</Item>
      </ul>

      <h2>Third-party research and links</h2>
      <p>
        Almost everything Graze shows describes work published elsewhere. Paper metadata
        comes from OpenAlex, Crossref, DOAJ, PubMed and similar sources, and links point to
        publishers and repositories Graze has no control over.
      </p>
      <p>
        <strong>
          Graze is not responsible for the content, accuracy, availability, or licensing of
          third-party research, external sites, or anything you find by following a link from
          here.
        </strong>{" "}
        Nor is it responsible for content posted by other users. Reports of content that
        breaks these terms are welcome at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>Availability</h2>
      <p>
        Graze is provided as-is, with no guarantee that it will be available, complete, or
        free of errors. It is run by one person as a non-commercial project; it may go
        offline, lose data, or stop entirely. Keep your own copy of anything you would be
        upset to lose. To the fullest extent the law allows, liability for loss arising from
        using the site is excluded — nothing here excludes liability that cannot lawfully be
        excluded, such as for death or personal injury caused by negligence, or for fraud.
      </p>

      <h2>Ending your account</h2>
      <p>
        You can ask for your account to be deleted at any time by emailing{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. Because posts and comments
        are contributions to a shared library, they may remain with authorship removed unless
        you ask for them to be taken down too.
      </p>
      <p>
        Accounts that break these terms may be suspended or removed, with notice and a chance
        to respond where it is reasonable to give one, and without notice where content is
        unlawful or actively harmful.
      </p>

      <h2>Changes and governing law</h2>
      <p>
        These terms may change; the date at the top shows when they last did, and continuing
        to use Graze means the new version applies.
      </p>
      <p>
        These terms are governed by the laws of British Columbia, Canada, without regard to
        conflict-of-law principles. If you are a consumer resident in the EU, UK, or
        elsewhere, mandatory consumer-protection laws where you live may still apply and can
        take precedence over this clause.
      </p>
    </LegalPage>
  );
}
